// Mocks generated by Mockito 5.4.6 from annotations
// in community_with_legends_mobile/test/features/profile/data/repositories/profile_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:community_with_legends_mobile/database/app_database.dart'
    as _i2;
import 'package:community_with_legends_mobile/src/features/profile/data/data_sources/profile_datasource.dart'
    as _i4;
import 'package:community_with_legends_mobile/src/features/profile/domain/models/hardware_model.dart'
    as _i8;
import 'package:community_with_legends_mobile/src/features/profile/domain/models/user_game_status_enum.dart'
    as _i9;
import 'package:community_with_legends_mobile/src/shared/data/data_sources/local/local_user_data_source_impl.dart'
    as _i10;
import 'package:community_with_legends_mobile/src/shared/domain/models/user_model.dart'
    as _i3;
import 'package:image_picker/image_picker.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAppDatabase_0 extends _i1.SmartFake implements _i2.AppDatabase {
  _FakeAppDatabase_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUser_1 extends _i1.SmartFake implements _i3.User {
  _FakeUser_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ProfileDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileDatasource extends _i1.Mock implements _i4.ProfileDatasource {
  MockProfileDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get baseUrl => (super.noSuchMethod(
        Invocation.getter(#baseUrl),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.getter(#baseUrl),
        ),
      ) as String);

  @override
  String get rootPem => (super.noSuchMethod(
        Invocation.getter(#rootPem),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.getter(#rootPem),
        ),
      ) as String);

  @override
  _i6.Future<Map<String, dynamic>> getUserProfile(int? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserProfile,
          [userId],
        ),
        returnValue:
            _i6.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<Map<String, dynamic>> getCurrentUserProfile() =>
      (super.noSuchMethod(
        Invocation.method(
          #getCurrentUserProfile,
          [],
        ),
        returnValue:
            _i6.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<Map<String, dynamic>> changeUserNickname(String? nickname) =>
      (super.noSuchMethod(
        Invocation.method(
          #changeUserNickname,
          [nickname],
        ),
        returnValue:
            _i6.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<Map<String, dynamic>> deleteUserAvatar() => (super.noSuchMethod(
        Invocation.method(
          #deleteUserAvatar,
          [],
        ),
        returnValue:
            _i6.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<bool> changeUserAvatar(_i7.XFile? avatar) => (super.noSuchMethod(
        Invocation.method(
          #changeUserAvatar,
          [avatar],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<Map<String, dynamic>> getUserHardware(int? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserHardware,
          [userId],
        ),
        returnValue:
            _i6.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<Map<String, dynamic>> updateUserHardware(_i8.Hardware? hardware) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserHardware,
          [hardware],
        ),
        returnValue:
            _i6.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<Map<String, dynamic>> deleteUserHardware(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteUserHardware,
          [id],
        ),
        returnValue:
            _i6.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<Map<String, dynamic>> addUserHardware(_i8.Hardware? hardware) =>
      (super.noSuchMethod(
        Invocation.method(
          #addUserHardware,
          [hardware],
        ),
        returnValue:
            _i6.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<Map<String, dynamic>> getUserGames(int? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserGames,
          [userId],
        ),
        returnValue:
            _i6.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<Map<String, dynamic>> getUserGame(int? userGameId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserGame,
          [userGameId],
        ),
        returnValue:
            _i6.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<Map<String, dynamic>> addGameToUserList(
    int? gameId,
    _i9.UserGameStatus? status,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addGameToUserList,
          [
            gameId,
            status,
          ],
        ),
        returnValue:
            _i6.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<Map<String, dynamic>> modifyUserGame(
    int? userGameId,
    int? gameId,
    _i9.UserGameStatus? status,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #modifyUserGame,
          [
            userGameId,
            gameId,
            status,
          ],
        ),
        returnValue:
            _i6.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<Map<String, dynamic>> deleteUserGame(int? userGameId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteUserGame,
          [userGameId],
        ),
        returnValue:
            _i6.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<Map<String, dynamic>> getUserProposals(int? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserProposals,
          [userId],
        ),
        returnValue:
            _i6.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<Map<String, dynamic>> createProposal(
    int? userId,
    int? gameId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createProposal,
          [
            userId,
            gameId,
          ],
        ),
        returnValue:
            _i6.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<Map<String, dynamic>> acceptProposal(int? proposalId) =>
      (super.noSuchMethod(
        Invocation.method(
          #acceptProposal,
          [proposalId],
        ),
        returnValue:
            _i6.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<Map<String, dynamic>> rejectProposal(int? proposalId) =>
      (super.noSuchMethod(
        Invocation.method(
          #rejectProposal,
          [proposalId],
        ),
        returnValue:
            _i6.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<Map<String, dynamic>> likeProposal(int? proposalId) =>
      (super.noSuchMethod(
        Invocation.method(
          #likeProposal,
          [proposalId],
        ),
        returnValue:
            _i6.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<Map<String, dynamic>> dislikeProposal(int? proposalId) =>
      (super.noSuchMethod(
        Invocation.method(
          #dislikeProposal,
          [proposalId],
        ),
        returnValue:
            _i6.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<Map<String, dynamic>> removeProposalVote(int? proposalId) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeProposalVote,
          [proposalId],
        ),
        returnValue:
            _i6.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<Map<String, dynamic>> postRequest({
    Map<String, dynamic>? body = const {},
    required String? urlPath,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #postRequest,
          [],
          {
            #body: body,
            #urlPath: urlPath,
          },
        ),
        returnValue:
            _i6.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<Map<String, dynamic>> deleteRequest({required String? urlPath}) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteRequest,
          [],
          {#urlPath: urlPath},
        ),
        returnValue:
            _i6.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<Map<String, dynamic>> getRequest({
    required String? urlPath,
    Map<String, String>? queryParams,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRequest,
          [],
          {
            #urlPath: urlPath,
            #queryParams: queryParams,
          },
        ),
        returnValue:
            _i6.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i6.Future<Map<String, dynamic>>);
}

/// A class which mocks [LocalUserDataSourceImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalUserDataSourceImpl extends _i1.Mock
    implements _i10.LocalUserDataSourceImpl {
  MockLocalUserDataSourceImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AppDatabase get localDatabase => (super.noSuchMethod(
        Invocation.getter(#localDatabase),
        returnValue: _FakeAppDatabase_0(
          this,
          Invocation.getter(#localDatabase),
        ),
      ) as _i2.AppDatabase);

  @override
  void cacheUser(_i3.User? user) => super.noSuchMethod(
        Invocation.method(
          #cacheUser,
          [user],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<void> cacheUserHardware(
    int? userId,
    List<_i8.Hardware>? hardware,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheUserHardware,
          [
            userId,
            hardware,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i3.User> getUserById(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getUserById,
          [id],
        ),
        returnValue: _i6.Future<_i3.User>.value(_FakeUser_1(
          this,
          Invocation.method(
            #getUserById,
            [id],
          ),
        )),
      ) as _i6.Future<_i3.User>);

  @override
  _i6.Future<List<_i8.Hardware>> getUserHardwareById(int? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserHardwareById,
          [userId],
        ),
        returnValue: _i6.Future<List<_i8.Hardware>>.value(<_i8.Hardware>[]),
      ) as _i6.Future<List<_i8.Hardware>>);

  @override
  _i6.Future<_i3.User> getCurrentUser() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentUser,
          [],
        ),
        returnValue: _i6.Future<_i3.User>.value(_FakeUser_1(
          this,
          Invocation.method(
            #getCurrentUser,
            [],
          ),
        )),
      ) as _i6.Future<_i3.User>);
}
