// Mocks generated by Mockito 5.4.6 from annotations
// in community_with_legends_mobile/test/features/feed/data/repositories/feed_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:community_with_legends_mobile/src/features/feed/data/data_sources/feed_data_source.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [FeedDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockFeedDataSource extends _i1.Mock implements _i2.FeedDataSource {
  MockFeedDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get baseUrl => (super.noSuchMethod(
        Invocation.getter(#baseUrl),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#baseUrl),
        ),
      ) as String);

  @override
  String get rootPem => (super.noSuchMethod(
        Invocation.getter(#rootPem),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#rootPem),
        ),
      ) as String);

  @override
  _i4.Future<Map<String, dynamic>> getPosts(int? page) => (super.noSuchMethod(
        Invocation.method(
          #getPosts,
          [page],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> getTrendingPosts() => (super.noSuchMethod(
        Invocation.method(
          #getTrendingPosts,
          [],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> getFilteredPosts(
    int? tagId,
    int? gameId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFilteredPosts,
          [
            tagId,
            gameId,
          ],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> createPost({
    required String? content,
    int? gameId,
    List<int>? tagIds,
    int? assetId,
    String? assetLink,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createPost,
          [],
          {
            #content: content,
            #gameId: gameId,
            #tagIds: tagIds,
            #assetId: assetId,
            #assetLink: assetLink,
          },
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> getFilteredGames(String? filter) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFilteredGames,
          [filter],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> getTags(String? filter) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTags,
          [filter],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<void> addPostReaction(int? postId) => (super.noSuchMethod(
        Invocation.method(
          #addPostReaction,
          [postId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> removePostReaction(int? postId) => (super.noSuchMethod(
        Invocation.method(
          #removePostReaction,
          [postId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<Map<String, dynamic>> reportPost(int? postId) =>
      (super.noSuchMethod(
        Invocation.method(
          #reportPost,
          [postId],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> deletePost(int? postId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deletePost,
          [postId],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> postRequest({
    Map<String, dynamic>? body = const {},
    required String? urlPath,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #postRequest,
          [],
          {
            #body: body,
            #urlPath: urlPath,
          },
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> deleteRequest({required String? urlPath}) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteRequest,
          [],
          {#urlPath: urlPath},
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> getRequest({
    required String? urlPath,
    Map<String, String>? queryParams,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRequest,
          [],
          {
            #urlPath: urlPath,
            #queryParams: queryParams,
          },
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);
}
